# -*- eval: (ansible) -*-
- include: vault.yml load=irc,users hosts=irc

- name: Configure IRC servers
  hosts: irc_servers
  become: false
  strategy: free
  tasks:
#    # Does not work on CoreOS, due to the fucked up
#    # Python install and lack of installable packages.
#    - name: Start the ircd container
#      docker_container:
#        name: ircd
#        state: started

    - name: Copy static configuration
      copy:
        src: "{{ item }}"
        dest: /home/core/unrealircd/{{ item | basename }}
      with_fileglob:
        - unrealircd/*.conf
        - unrealircd/ircd.motd
      notify: [rehash ircd]

    - name: Generate templated configuration
      template:
        src: "{{ item }}"
        dest: /home/core/unrealircd/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
        - unrealircd/*.j2
      notify: [rehash ircd]

  handlers:
    - name: rehash ircd
      command: docker exec -i ircd /unrealircd/unreal rehash

- name: Configure IRC services
  hosts: services.irc.hashbang.sh
  become: true
  tasks:

    - name: Copy static configuration
      copy:
        src: "{{ item }}"
        dest: /home/core/anope/config/{{ item | basename }}
      with_fileglob:
        - anope/*.conf
      notify: [Reload anope config]

    - name: Generate templated configuration
      template:
        src: "{{ item }}"
        dest: /home/core/anope/config/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
        - anope/*.j2
      notify: [Reload anope config]

  handlers:
    - name: Reload anope config
      command: docker exec -i irc-services pkill -HUP services
