# -*- eval: (ansible) -*-
- include: vault.yml load=ldap hosts=ldap.hashbang.sh

- name: Disable the account in LDAP
  hosts: ldap.hashbang.sh
  gather_facts: False
  tasks:
    - ldap_attr:
        server_uri: ldaps://ldap.hashbang.sh
        bind_dn: "{{ ldap.admin.dn }}"
        bind_pw: "{{ ldap.admin.password }}"

        dn: uid={{ user | mandatory }},ou=People,dc=hashbang,dc=sh
        name: loginShell
        state: exact
        values: /usr/sbin/nologin
      delegate_to: localhost

- hosts: shell_servers
  become: true
  tasks:
    - name: Invalidate SSSd cache for {{ user }}
      command: sss_cache -u {{ user }}
      changed_when: false
      ignore_errors: yes

    - name: Terminate sessions for {{ user }}
      command: loginctl terminate-user {{ user }}
      register: terminate
      failed_when: |
        'Could not terminate user: No user' not in terminate.stderr
        and terminate|failed
      changed_when: terminate.stderr == "" and terminate|success
