# -*- eval: (ansible) -*-
- include: vault.yml load=ldap hosts=ldap.hashbang.sh

- name: Parse parameters
  hosts: ldap.hashbang.sh,shell_servers
  gather_facts: no
  tasks:
    - name: Parse users list
      set_fact:
        user_list: "{{ users.split(',') }}"

- name: Disable the account in LDAP
  hosts: ldap.hashbang.sh
  gather_facts: False
  tasks:
    - ldap_attr:
        server_uri: ldaps://ldap.hashbang.sh
        bind_dn: "{{ ldap.admin.dn }}"
        bind_pw: "{{ ldap.admin.password }}"

        dn: uid={{ item }},ou=People,dc=hashbang,dc=sh
        name: loginShell
        state: exact
        values: /usr/sbin/nologin
      delegate_to: localhost
      with_items: "{{ user_list }}"

- hosts: shell_servers
  become: true
  gather_facts: no
  tasks:
    - name: Invalidate SSSd cache entries
      command: sss_cache -u {{ item }}
      with_items: "{{ user_list }}"
      changed_when: false
      ignore_errors: yes

    - name: Terminate user sessions
      command: loginctl terminate-user {{ item }}
      register: terminate
      with_items: "{{ user_list }}"
      failed_when: |
        'Could not terminate user: No user' not in terminate.stderr
        and terminate|failed
      changed_when: terminate.stderr == "" and terminate|success
