# -*- eval: (ansible) -*-
- name: Pull latest /etc files
  hosts: shell_servers
  tasks:
    - name: Fetch changes
      command: etckeeper vcs fetch origin master
      register: etc_fetch

    - block:
        - name: Create a temporary GNUPGHOME
          command: mktemp -d
          register: tmpdir
          changed_when: false

        - name: Copy the dummy GnuPG config
          copy:
            dest: "{{ tmpdir.stdout + '/gpg.conf' }}"
            content: |
              # Never, ever, ever do this in your personal gpg.conf
              # However, this is OK when you know you use an empty GNUPGHOME
              keyring /var/lib/hashbang/admins.gpg
              trust-model always
          changed_when: false

        - name: Check update signature
          command: etckeeper vcs verify-commit origin/master
          environment:
            GNUPGHOME: "{{ tmpdir.stdout }}"

        - name: Fast-forward changes
          command: etckeeper vcs merge --ff-only origin/master
          register: etc
          notify: etc changed
          changed_when: "'Already up-to-date' not in etc.stdout"

      always:
        - name: Remove the temporary GNUPGHOME
          file: path={{ tmpdir.stdout }} state=absent
          changed_when: false

      when: etc_fetch.changed


  handlers:
    - name: etc changed
      block:
        - name: Apply file permissions in /etc
          command: etckeeper init

        - name: Push new /etc state
          command: etckeeper push

        - name: Update GnuPG keyring
          command: /etc/cron.daily/gpg-keyring


- name: Update/Sync system packages
  hosts: shell_servers
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:   update_cache=yes
    - name: Update dpkg cache
      shell: apt-cache dumpavail | dpkg --update-avail
      tags: [skip_ansible_lint]

    - block:
        - name: Set dpkg selections
          shell:   dpkg --clear-selections && dpkg --set-selections < /etc/packages.txt
        - name: Apply dpkg selections
          command: apt-get dselect-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -qy
          environment:
            DEBIAN_FRONTEND: noninteractive
      when: etc.changed
      tags: [skip_ansible_lint] # The apt module doesn't support this

    - name: Upgrade packages
      apt: upgrade=dist
      register: apt_upgrade

    - name: Purge uninstalled packages
      command: aptitude purge -y -q ~c
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: etc.changed or apt_upgrade.changed
      tags: [skip_ansible_lint] # W0016 triggers, but can't be a handler

    - name: Clean the apt package cache
      command: apt-get clean
      changed_when: false
